version: '3.5'
services:
    tomaco:
        build: .
        container_name: tomaco
        command: >
            sh -c "npm run run & flask run --host=0.0.0.0 --port=8080"
        volumes:
            - ./:/app
        ports:
            - "8080:8080"
            - "9485:9485" # JavaScript live reload
        environment:
            FLASK_APP: "tomaco.wsgi:application"
            FLASK_DEBUG: "1"
            GITHUB_CLIENT_ID: ""
            GITHUB_CLIENT_SECRET: ""
            DATABASE_URL: "postgresql://root@postgres/tomaco_dev"
        stdin_open: true
        tty: true
        depends_on:
            - postgres
        links:
            - postgres

    postgres:
        image: postgres:latest
        container_name: postgres
        restart: always
        environment:
            - POSTGRES_USER=root
            - POSTGRES_DB=tomaco_dev
        volumes:
            - "./data/postgres:/var/lib/postgresql/data"
        ports:
            - 5432:5432
