version: '3.5'
services:
    app:
        build: .
        container_name: tomaco
        command: >
            sh -c "npm run run & flask run --host=0.0.0.0 --port=8080"
        volumes:
            - ./:/app
        ports:
            - "8080:8080"
            - "9485:9485" # JavaScript live reload
        environment:
            FLASK_APP: "tomaco.wsgi:application"
            FLASK_DEBUG: "1"
        stdin_open: true
        tty: true
