version: "3.5"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_DB=tomaco_dev
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    ports:
      - 5432:5432
  tomaco:
    build: .
    container_name: tomaco
    volumes:
      - ./:/app
    ports:
      - "8080:8080"
      - "9485:9485" # JavaScript live reload
    environment:
      FLASK_APP: "tomaco.wsgi:application"
      FLASK_DEBUG: "1"
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      DATABASE_URL: "postgresql://root@postgres/tomaco_dev"
    entrypoint: bin/docker-entrypoint.sh
    stdin_open: true
    tty: true
    depends_on:
      - postgres
    links:
      - postgres
